---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution in ["Ubuntu", "Debian"]

  - name: intall apache2 package
    apt:
      name: apache2
      state: latest
    when: ansible_distribution_file_variety == "Debian"
  
  - name: add php support for apache
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: update repository index
    dnf:
      update_cache: yes
    when: ansible_distribution in ["CentOS", "RedHat"]

  - name: intall apache2 package
    dnf:
      name: httpd
      state: latest
    when: ansible_distribution_file_variety == "RedHat"
    
  - name: add php support for apache
    dnf:
      name: php
      state: latest
    when: ansible_distribution == "CentOS"